### DISCUSSION TITLE
Cannot make above v1.44.2

### DISCUSSION THREAD

**Discussion by galaxy001** [libuv/libuv#4294] [Q&A]
* **Version**: 1.45.0, 1.47.0
* **Platform**: Linux 5.15.0-88-generic Ubuntu SMP

Run `git checkout v1.45.0; ./autogen.sh; ./configure; make -j`

```
src/unix/linux.c: In function 'uv_uptime':
src/unix/linux.c:1465:21: error: 'CLOCK_BOOTTIME' undeclared (first use in this function); did you mean 'CLOCK_REALTIME'?
 1465 |   if (clock_gettime(CLOCK_BOOTTIME, &now))
      |                     ^~~~~~~~~~~~~~
      |                     CLOCK_REALTIME
```

make v1.44.2 is OK.

micromamba with env:
```yaml
name: gcompiler
channels:
  - conda-forge
  - nodefaults
dependencies:
  - binutils
  - gxx   # gxx depends on gcc
  - gfortran
  - clangxx
  - pkg-config
  - cmake
  - libuv[version='<1.46']  # 1.44.2 OK, 1.46.0 undefined reference to `sendmmsg'
  - kernel-headers_linux-64
```
