### ISSUE TITLE
make check failed

### ISSUE THREAD

**Issue by winksaville** [libuv/libuv#583]
Reporting a make check failure as requested, the problem appears to be reproducible. I tested ToT as of today and then checked out v1.7.5 and the same failures occurred. Here is my uname output
```
$ uname -a
Linux wink-envy 4.2.3-1-ARCH #1 SMP PREEMPT Sat Oct 3 18:52:50 CEST 2015 x86_64 GNU/Linux
```
And here is the log as sent to the screen:
```
make[1]: Entering directory '/home/wink/foss/libuv'
[%   0|+   0|-   0|T   0|S   0]: platform_output
Output from process `platform_output`:
uv_get_process_title: /home/wink/foss/libuv/test/.libs/lt-run-tests
uv_cwd: /home/wink/foss/libuv
uv_resident_set_memory: 1089536
uv_uptime: 206104.000000
uv_getrusage:
  user: 0 sec 0 microsec
  system: 0 sec 0 microsec
uv_cpu_info:
  model: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  speed: 2570
  times.sys: 8573400
  times.user: 23815100
  times.idle: 910277900
  times.irq: 0
  times.nice: 2849300
  model: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  speed: 2548
  times.sys: 8096400
  times.user: 29123400
  times.idle: 44723400
  times.irq: 0
  times.nice: 2813700
  model: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  speed: 2615
  times.sys: 6754300
  times.user: 24937700
  times.idle: 45109800
  times.irq: 0
  times.nice: 2681100
  model: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  speed: 2565
  times.sys: 6390200
  times.user: 23519200
  times.idle: 45253400
  times.irq: 0
  times.nice: 2755900
uv_interface_addresses:
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: wlo1
  internal: 0
  physical address: 34:e6:ad:b5:a5:40
  address: 192.168.0.176
  netmask: 255.255.0.0
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: wlo1
  internal: 0
  physical address: 34:e6:ad:b5:a5:40
  address: fd93:81d:e056:1:36e6:adff:feb5:a540
  netmask: ffff:ffff:ffff:ffff::
  name: wlo1
  internal: 0
  physical address: 34:e6:ad:b5:a5:40
  address: fe80::36e6:adff:feb5:a540
  netmask: ffff:ffff:ffff:ffff::
=============================================================
[%  61|+ 168|-   0|T   0|S   0]: getaddrinfo_fail
`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
=============================================================
[%  61|+ 168|-   1|T   0|S   0]: getaddrinfo_fail_sync
`getaddrinfo_fail_sync` failed: exit code 134
Output from process `getaddrinfo_fail_sync`:
Assertion failed in test/test-getaddrinfo.c on line 108: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy", NULL, NULL)
=============================================================
[%  86|+ 236|-   2|T   0|S   0]: fs_event_watch_dir_recursive
`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================
[% 100|+ 272|-   2|T   0|S   1]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:3985: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/wink/foss/libuv'
Makefile:4241: recipe for target 'check-am' failed
make: *** [check-am] Error 2
```
